---

- name: Cobbler sync
  ansible.builtin.command: cobbler sync

- name: Restart cobblerd
  ansible.builtin.systemd:
   name: cobblerd
   state: restarted

- name: Restart httpd
  ansible.builtin.systemd:
   name: httpd
   state: restarted

- name: Restart xinetd
  ansible.builtin.systemd:
   name: xinetd
   state: restarted

...
