---
- name: Cobbler sync
  ansible.builtin.command: cobbler sync

- name: Cobbler mkgrub
  ansible.builtin.command: /usr/share/cobbler/bin/mkgrub.sh

- name: Restart_cobblerd
  ansible.builtin.systemd:
   name: cobblerd
   state: restarted

- name: Restart_httpd
  ansible.builtin.systemd:
   name: httpd
   state: restarted
   enabled: true
...
