---

# D Simpson 2021,2023 ds-04

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

- block:

   - name: Check each repo exists in cobbler
     ansible.builtin.shell: cobbler repo report --name={{ item.name }}
     ignore_errors: true
     changed_when: "'No repo' in repo_check.stdout"
     register: repo_check
     with_items:
      - "{{ cobbler_repos }}"

   - name: Cobbler repo add
     ansible.builtin.command: cobbler repo add --name={{ item.item.name }} --arch={{ item.item.arch | default('x86_64') }} --mirror={{ item.item.mirror }} --comment={{ item.item.comment | default('') }} --breed={{ item.item.breed | default('yum') }} --keep-updated={{ item.item.keep_updated | default('Y') }}
     when: item.changed
     with_items:
      - "{{ repo_check.results }}"

   # --priority={{ item.priority | default(99) }} needs added but similar issue to https://github.com/cobbler/cobbler/issues/2722
   - name: Cobbler repo edit to update rpm-list, keep-updated(def:Y), comment, yumopts(def:--no-check-gpg)
     ansible.builtin.command: cobbler repo edit --name={{ item.name }} --mirror={{ item.mirror }} --rpm-list={{ item.rpm_list | default('') }} --mirror-locally={{ item.mirror_locally | default('Y') }} --keep-updated={{ item.keep_updated | default('Y') }} --comment={{ item.comment | default('') }} --yumopts={{ item.yumopts | default('--no-check-gpg') }}
     with_items:
      - "{{ cobbler_repos }}"

   # future enhancement is to check exist first
   - name: Cobbler repo remove
     ansible.builtin.command: cobbler repo remove --name={{ item.name }}
     with_items:
      - "{{ cobbler_removed_repos }}"
     when:
      - (cobbler_removed_repos is defined) and (cobbler_removed_repos|length > 0)

   - name: Cobbler repo list
     ansible.builtin.command: cobbler repo list
     register: repo_list

   - name: Show repo list
     ansible.builtin.debug:
      msg: "{{ repo_list }}"

  become: true

...
