---

# D Simpson 2021,2023 ds-04
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

- name: Import setup_cobbler3x.yml
  ansible.builtin.import_tasks: setup_cobbler3x.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (ansible_os_family == "RedHat" or ansible_distribution == 'AlmaLinux') and ansible_distribution_major_version|int >= 8
  tags:
    - setup_server

- name: Import configure_cobbler3x.yml
  ansible.builtin.import_tasks: configure_cobbler3x.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (ansible_os_family == "RedHat" or ansible_distribution == 'AlmaLinux') and ansible_distribution_major_version|int >= 8
  tags:
    - configure_server

- name: Import cobbler_distro.yml
  ansible.builtin.import_tasks: cobbler_distro.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (ansible_os_family == "RedHat" or ansible_distribution == 'AlmaLinux') and ansible_distribution_major_version|int >= 8
  tags:
    - distros

# If you don't use debian then ensure Deploy_debian is changed in defaults
- name: Import cobbler_debian_netinst_fix.yml
  ansible.builtin.import_tasks: cobbler_debian_netinst_fix.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (ansible_os_family == "RedHat" or ansible_distribution == 'AlmaLinux') and ansible_distribution_major_version|int >= 8
    - Deploy_debian
  tags:
    - debian_fix

# If cobbler_profiles isn't defined skip
- name: Import cobbler_profiles.yml
  ansible.builtin.import_tasks: cobbler_profiles.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (ansible_os_family == "RedHat" or ansible_distribution == 'AlmaLinux') and ansible_distribution_major_version|int >= 8
    - (cobbler_profiles is defined) and (cobbler_profiles|length > 0)
  tags:
    - profiles

- name: Import cobbler_repos.yml
  ansible.builtin.import_tasks: cobbler_repos.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (ansible_os_family == "RedHat" or ansible_distribution == 'AlmaLinux') and ansible_distribution_major_version|int >= 8
  tags:
    - repos

- name: Import cobbler_systems.yml
  ansible.builtin.import_tasks: cobbler_systems.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (ansible_os_family == "RedHat" or ansible_distribution == 'AlmaLinux') and ansible_distribution_major_version|int >= 8
  tags:
    - systems

...
