---

#D Simpson 2021, ds-04

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

- block:

  - name: dnf install epel-release
    dnf:
     name: epel-release
     state: present

  - name: dnf enable module cobbler
    command: dnf -y module enable cobbler

  - name: Install cobbler via dnf
    dnf:
     name: cobbler
     state: latest

  - name: Install cobbler-web via dnf with --allowerasing for python-django
    command: dnf -y install cobbler-web --allowerasing
    when: install_cobbler_web != 'False'

  - name: install cobbler packages (dependencies)
    dnf:
     name:
      - jq #not needed by cobbler, but needed by this role
      - createrepo_c
      - debmirror
      - dnf-plugins-core
      - git
      - httpd
      - httpd-devel
      - make
      - mod_ssl
      - openssl
      - pykickstart
      - python3-devel
      - python3-librepo #needed for reposync on Centos 8 derived
      - python3-mod_wsgi
      - python3-pyyaml
      - rsync
      - syslinux #used for boot-loaders
      - tftp-server
      - xinetd # xinetd to manage tftp
      - xorriso
      - yum-utils
     state: installed

  - name: Install multiple python packages
    pip:
     name:
      - Cheetah3
      - coverage
      - netaddr
      - schema
      - Sphinx
     executable: pip3

  - name: set server in /etc/cobbler/settings
    lineinfile:
     path: /etc/cobbler/settings
     backup: 'yes'
     regexp: '^server:'
     line: 'server: {{ inventory_hostname }}'
    notify:
     - restart cobblerd

  - name: set next server in /etc/cobbler/settings
    lineinfile:
     path: /etc/cobbler/settings
     backup: 'yes'
     regexp: '^next_server:'
     line: 'next_server: {{ inventory_hostname }}'
    notify:
     - restart cobblerd

  - name: set reposync_flags in /etc/cobbler/settings for CENTOS8 based
    lineinfile:
     path: /etc/cobbler/settings
     backup: 'yes'
     regexp: '^reposync_flags:'
     line: 'reposync_flags: "-n --delete"'
    notify:
     - restart cobblerd

  - name: Copy xinetd tftp file
    copy:
     src: tftp
     dest: /etc/xinetd.d/tftp
     mode: '0600'
     backup: 'yes'
     owner: root
     group: root
    notify:
     - restart xinetd

  - name: setsebool -P httpd_can_network_connect true and persist
    seboolean:
     name: httpd_can_network_connect
     state: 'yes'
     persistent: 'yes'

  - name: Ensure httpd error AH0058 does not occur (FQDN) - edit /etc/httpd/conf.d/ssl.conf
    lineinfile:
     path: /etc/httpd/conf.d/ssl.conf
     backup: 'yes'
     regexp: '^ServerName'
     line: 'ServerName {{ inventory_hostname }}:443'
    notify:
     - restart httpd

  - name: Ensure systemd enable set on cobblerd, httpd, xinetd
    systemd:
     name: "{{ item }}"
     state: started
     enabled: 'yes'
    with_items:
     - httpd
     - cobblerd
     - xinetd

  - name: get cobbler version
    shell: cobbler --version | grep Cobbler | grep -o [0-9].[0-9].[0-9]
    register: cobbler_ver

  - name: Version 3.2.0 - Copy deprecation warning for get-loaders to /etc/profile.d
    copy:
     src: cobbler_320.sh
     dest: /etc/profile.d/cobbler_320.sh
     mode: '0644'
     owner: root
     group: root
    when: cobbler_ver.stdout == "3.2.0"

  #github issue 2708
  - name: Version 3.2.0 - Copy syslinux files to /var/lib/cobbler/loaders
    copy:
     remote_src: 'yes'
     src: "/usr/share/syslinux/{{ item }}"
     dest: "/var/lib/cobbler/loaders/{{ item }}"
     mode: '0644'
     owner: root
     group: root
    with_items:
     - ldlinux.c32
     - libcom32.c32
     - libutil.c32
     - menu.c32
     - pxelinux.0
    when: cobbler_ver.stdout == "3.2.0"
    notify:
     - cobbler sync

  become: 'True'

...
